- .github/workflows/ci.yml
- .gitignore
- .vscode/extensions.json
- README.md
- nx.json
- package-lock.json
- package.json
- packages/frontend-analytics/package.json
- packages/frontend-language-toggle/package.json
- packages/frontend-passthrough-headers/package.json
This adds the boilerplate to the monorepo...
I have tested the packages structure using `npx nx graph`
and I can see these are initialised with a package.json
> DFC-238: Add NX scaffolding

- .github/workflows/cd.yml
- README.md
- nx.json
Added a Continuous Deployment (CD) workflow for our Nx monorepo. This workflow automates the release process for the specified packages based on user inputs.
- Added workflow_dispatch trigger for manual execution.
- Implemented options for selecting the target package and increment type.
- Configured job to prepare the branch for main by setting up main branch tracking and configuring git user.
- Integrated Nx commands for setting SHAs, linting, testing, and building affected packages.
- Published packages to npm registry based on user inputs.
- Changes Made
- Added CD workflow YAML file.
- Updated README.md with instructions for triggering the CD workflow.
- Set SHAs for Affected Packages: Implemented the use of nrwl/nx-set-shas@v4 to set SHAs for affected packages.This step ensures that …
>  DI Components | (MVP) Create a CD pipeline to publish to NPM

- .github/workflows/cd.yml
- package-lock.json
- packages/alpha-component/.gitignore
- packages/alpha-component/README.md
- packages/alpha-component/jest.config.ts
- packages/alpha-component/language-param-setter.test.ts
- packages/alpha-component/language-param-setter.ts
- packages/alpha-component/language-select.yaml
- packages/alpha-component/macro.njk
- packages/alpha-component/package.json
- packages/alpha-component/rollup.config.js
- packages/alpha-component/stylesheet/styles.css
- packages/alpha-component/template.njk
- packages/alpha-component/template.test.ts
- packages/alpha-component/tsconfig.json
- packages/alpha-component/utils/jestHelpers.ts
This is a PR to add the dummy package to the one login component repository - to allow for CD pipeline testing
This will be here
https://github.com/govuk-one-login/govuk-one-login-frontend/actions/workflows/cd.yml 
The alpha component should appear in the dropdown once merged, then we can test the CD pipeline
> Add dummy package

- .github/workflows/cd.yml
Amends CD pipeline step for release
> Add changes to CD pipeline

- .github/workflows/cd.yml
Amend permissions for actions to be able to write
> Amend actions permission to be able to write

- .github/workflows/cd.yml
> feat: update CD creds

- .github/workflows/cd.yml
This PR amends the NX CI pipeline command to run the specific project selected in the CD
> Dfc 606 di components test package release process 2

- packages/alpha-component/package.json
Amend build command to configure when no tests are present in the folder
> Replace build command to cater for empty files

- .github/workflows/cd.yml
Correct ternary operator on CD pipeline
- changes comparison operator
- changes boolean to string
> Correct ternary operator

- packages/alpha-component/package.json
Rename package to use organisation name
> rename package to govuk onelogin

- package.json
- packages/alpha-component/package.json
Add publish config to alpha component and revert public change on root package.json
> Add publish config to alpha component

- .eslintignore
- .prettierignore
- .vscode/settings.json
- README.md
- jest.config.ts
- jest.preset.js
- nx.json
- package-lock.json
- package.json
- packages/automation/README.md
- packages/automation/generators.json
- packages/automation/jest.config.ts
- packages/automation/package.json
- packages/automation/project.json
- packages/automation/src/generators/generate-component/files/package.json.template
- packages/automation/src/generators/generate-component/files/rollup.config.js.template
- packages/automation/src/generators/generate-component/files/src/index.ts.template
- packages/automation/src/generators/generate-component/generator.spec.ts
- packages/automation/src/generators/generate-component/generator.ts
- packages/automation/src/generators/generate-component/schema.d.ts
- packages/automation/src/generators/generate-component/schema.json
- packages/automation/tsconfig.json
- packages/automation/tsconfig.lib.json
- packages/automation/tsconfig.spec.json
- tsconfig.base.json
**Feedback required: 
Please confirm whether I the package.json dependencies are correct and I have added the correct template files**
This PR introduces an automation feature for creating components using the command line tool `nx g automation:generate-component`. It simplifies the setup process by automatically generating essential files such as `package.json`, `index.ts`, `rollup.config.js`, and `project.json`.
- Installed the NX package with `npm install nx`.
- Added `@nx/plugin` as a development dependency and made it available workspace-wide at the root level using `npm install @nx/plugin -D -w`.
- Configured a workspace plugin named `automation`.
- Created a generator named `generate-component`, which includes template files.
- Customised options for users during component …
> DFC-254 | Create Command Line Tool to Scaffold Components

- .github/workflows/ci.yml
- .gitignore
- packages/alpha-app/src/app.js
- packages/frontend-vital-signs/README.md
Add a readme file to the repo.
README Includes:
- Context of what the package is
- A quick start guide
- Documentation of what each of the input parameters are, and default values
- [DFC-608](https://govukverify.atlassian.net/browse/DFC-608)
[DFC-608]: https://govukverify.atlassian.net/browse/DFC-608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DFC-608 |  Create README for frontendVitalsMonitoring package

- packages/frontend-vital-signs/package.json
This makes the frontend-vital-signs package public so that it can be deployed to npm.
> feat: make frontend-vital-signs package public

- CODEOWNERS
Adds a CODEOWNERS file to the repository
- [DFC-670](https://govukverify.atlassian.net/browse/DFC-670)
[DFC-670]: https://govukverify.atlassian.net/browse/DFC-670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DFC-670] - Add CODEOWNERS file

- .github/workflows/cd.yml
- packages/alpha-app/package.json
This adds an option to the CD pipeline to let us dry-run a release and preview the output.
> feat: add ability to dry run release

- packages/frontend-language-toggle/README.md
Small readme update detailing the breaking change 
https://govukverify.atlassian.net/browse/DFC-693
> Dfc 693 dfc language toggle update readme in absence of change log update

- packages/alpha-app/package.json
- packages/alpha-app/src/config/nunjucks.js
- packages/alpha-app/test/browser/features/v1/analytics/ga4/ga4NavigationEvent.feature
- packages/alpha-app/test/browser/step_definitions/common.js
Add integration testing for the back link event triggered by our navigationTracker in the analytics package
- [DFC-412](https://govukverify.atlassian.net/browse/DFC-412)
[DFC-412]: https://govukverify.atlassian.net/browse/DFC-412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DFC-412:  Add integration tests for analytics Back Link event

- .github/workflows/commitlint.yml
- .husky/commit-msg
- commitlint.config.js
- jest.preset.js
- nx.json
- package-lock.json
- package.json
Adds commitlint as a dev dependency to enforce conventional commits
- [DFC-704](https://govukverify.atlassian.net/browse/DFC-704)
[DFC-704]: https://govukverify.atlassian.net/browse/DFC-704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DFC-704): add commitlint

- CONTRIBUTING.md
- README.md
Update readme and add contribution guide to the mono repo.
README Updates:
- Context of what the mono repo is (already present)
- A quick start guide (already present)
- A guide to publishing packages
- A guide for how other teams can contribute code to the mono repo
Contribution Guide
- Outline the branch protections
- Conventional commits explanation
- Detailed explanation of how and where changes need to be tested (CRI/non CRI)
- [DFC-249](https://govukverify.atlassian.net/browse/DFC-249)
[DFC-249]: https://govukverify.atlassian.net/browse/DFC-249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(DFC-249): Update README and add contributing file

- packages/frontend-language-toggle/README.md
Update Language Toggle README guide with information on the javascript breaking change.
- [DFC-722](https://govukverify.atlassian.net/browse/DFC-722)
[DFC-722]: https://govukverify.atlassian.net/browse/DFC-722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(DFC-722): update Language Toggle README with info on JS import path breaking change

- packages/automation/src/generators/generate-component/files/package.json.template
- packages/frontend-analytics/package.json
- packages/frontend-language-toggle/package.json
- packages/frontend-passthrough-headers/package.json
- packages/frontend-vital-signs/package.json
PR adds publish config to existing and future packages
https://govukverify.atlassian.net/browse/DFC-724
> feat(724): update publish config settings

- package-lock.json
- packages/alpha-app/package.json
- packages/alpha-app/src/app.js
> chore(chore): upgrade alpha-app to use latest version of frontend-analytics package

- packages/frontend-analytics/README.md
Small PR to detail a suggested approach on how target repositories can pass in a variable to specify global vs page level isDataSensitive flags
https://govukverify.atlassian.net/browse/DFC-695
> Dfc 695 ga4 new functionality move is data sensitive flag to page level

- packages/alpha-app/src/app.js
- packages/frontend-language-toggle/README.md
- packages/frontend-language-toggle/src/__test__/language-param-setter.test.ts
- packages/frontend-language-toggle/src/language-param-setter.ts
As part of the latest Language Toggle improvements, the active URL is now constructed using new URL() with string concatenation. While error handling is currently managed at the middleware level, adding error handling during the URL parsing process provides a more reliable solution.
- An if block has been added to the `addLanguageParam` function. If the currentUrl  cannot be assigned correctly (resulting in the url parameter for the lang toggle template being undefined), the href value of the toggle link is set to "#invalid-url-lang-toggle". This ensures that the user is not directed to an incorrect URL, keeps them on the page, and allows them to continue navigating freely.
- README documentation has also been updated to encourage teams to update their implementation to add error handling …
> DFC-581 : add error handling for adding/setting lang param in the URL

- .github/workflows/deprecate.yml
- README.md
Adds a new github workflow to automate package deprecation
- [DFC-714](https://govukverify.atlassian.net/browse/DFC-714)
[DFC-714]: https://govukverify.atlassian.net/browse/DFC-714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DFC-714]: Add deprecation workflow

- packages/frontend-vital-signs/package.json
This fixes a types import path issue.
> fix: update import paths for vital signs

- packages/frontend-analytics/README.md
- packages/frontend-asset-loader/README.md
- packages/frontend-language-toggle/README.md
- packages/frontend-passthrough-headers/README.md
- packages/frontend-vital-signs/README.md
Updating our ReadMe Files to include SonarQube badges.
- [DFC-729](https://govukverify.atlassian.net/browse/DFC-729)
[DFC-729]: https://govukverify.atlassian.net/browse/DFC-729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(729): Adding sonarcloud badges to readme files

- .github/workflows/deprecate.yml
- .github/workflows/release.yml
- .github/workflows/static-analysis.yml
- README.md
- packages/frontend-ui/README.md
- packages/frontend-ui/package.json
- packages/frontend-ui/project.json
- packages/frontend-ui/rollup.config.js
- packages/frontend-ui/sonar-project.properties
- packages/frontend-ui/src/index.ts
Creation of the frontend-ui package
- [DFC-738](https://govukverify.atlassian.net/browse/DFC-738)
[DFC-738]: https://govukverify.atlassian.net/browse/DFC-738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DFC-738): created frontend-ui package

- packages/frontend-ui/project.json
Updated name in project.json
- [DFC-738](https://govukverify.atlassian.net/browse/DFC-738)
[DFC-738]: https://govukverify.atlassian.net/browse/DFC-738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: updated naming in project.json

- packages/frontend-analytics/README.md
Updates our README.md with coding examples for implementing the isDataSensitive flag at page level instead of globally
> Chore(analytics-frontend): Update readme with isDataSensitive example for setting at page level

- packages/frontend-analytics/README.md
Updating the readme to reflect version 3.0.1
> chore: update readme

- packages/frontend-analytics/sonar-project.properties
Updates the sonar-project.properties file to include `frontend-analytics` as the package name instead of `di-fec-ga4`
> chore(analytics): Update sonar projectName

- packages/frontend-passthrough-headers/package.json
Issue spotted during pair programming with FEC team, minor fix.
> fix(headers): Updating package.json main, module and export paths plus minor config

- package-lock.json
- packages/alpha-app/public/stylesheets/application-frontendUi.css
- packages/alpha-app/src/views/common/base.njk
- packages/frontend-ui/components/skip-link/README.md
- packages/frontend-ui/components/skip-link/macro.njk
- packages/frontend-ui/components/skip-link/skip-link.yaml
- packages/frontend-ui/components/skip-link/template.njk
- packages/frontend-ui/locales/cy/translation.json
- packages/frontend-ui/locales/en/translation.json
- packages/frontend-ui/src/index.ts
- [DFC-749](https://govukverify.atlassian.net/browse/DFC-749)
[DFC-749]: https://govukverify.atlassian.net/browse/DFC-749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(dfc-749): skip link in frontend-ui package

- packages/frontend-ui/components/_all.scss
- packages/frontend-ui/components/skip-link/template.njk
- packages/frontend-ui/src/__tests__/index.spec.ts
- [DFC-749](https://govukverify.atlassian.net/browse/DFC-749)
[DFC-749]: https://govukverify.atlassian.net/browse/DFC-749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(dfc-749): build fail due to forward slash

- .github/workflows/release.yml
> fix: added npm installs for linux

- package-lock.json
- package.json
- packages/alpha-app/src/app.js
- packages/alpha-app/src/views/common/base.njk
- packages/frontend-device-intelligence/jest.config.js
- packages/frontend-device-intelligence/jest.setup.js
- packages/frontend-device-intelligence/package.json
- packages/frontend-device-intelligence/src/components/fonts/fonts.test.ts
- packages/frontend-device-intelligence/src/components/fonts/fonts.ts
- packages/frontend-device-intelligence/src/fingerprint/functions.test.ts
- packages/frontend-device-intelligence/src/fingerprint/functions.ts
- packages/frontend-device-intelligence/src/index.test.ts
- packages/frontend-device-intelligence/src/utils/hash.test.ts
- [DFC-818](https://govukverify.atlassian.net/browse/DFC-818)
1. Build the packages
2. Test in the alpha-app package
3. Inspect element > Application > Look at the cookie called "device_intelligence_fingerprint" 
4. Take the cookie value
5. In Console, You can use the atob mechanism to see the encoded value
6. Once you can view the un-encoded value then you will see something like this at the end of the fingerprint:
"fonts":{"fontHash":"b582964e91622e755c423ad99c8ec9b4"},"thumbmark":{"deviceHash":"9c69a4ffa43f3bd072ddce5b4c2e424e"}}'
[DFC-818]: https://govukverify.atlassian.net/browse/DFC-818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DFC-818): Font and Hash fields with RFC

- packages/alpha-app/src/config/gtmMiddleware.js
- packages/alpha-app/src/views/common/base.njk
- packages/frontend-analytics/README.md
- packages/frontend-analytics/package.json
- packages/frontend-analytics/src/analytics/formResponseTracker/formResponseTracker.ts
- packages/frontend-analytics/src/index.test.ts
- packages/frontend-analytics/src/index.ts
This adds upgrade guidance for V4 of the frontend-analytics package.
- [DFC-828](https://govukverify.atlassian.net/browse/DFC-828)
[DFC-828]: https://govukverify.atlassian.net/browse/DFC-828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DFC-828): add isPageDataSensitive docs

- packages/frontend-analytics/src/analytics/navigationTracker/navigationTracker.interface.ts
- packages/frontend-analytics/src/analytics/navigationTracker/navigationTracker.test.ts
- packages/frontend-analytics/src/analytics/navigationTracker/navigationTracker.ts
- packages/frontend-analytics/src/utils/dataScrapers.ts
- [DFC-655](https://govukverify.atlassian.net/browse/DFC-655)
[DFC-655]: https://govukverify.atlassian.net/browse/DFC-655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(analytics/DFC-655): extend navigation tracker types to include anchor elements

- packages/frontend-device-intelligence/LICENSE
- packages/frontend-device-intelligence/package.json
MIT License added to the device intelligence package
- [DFC-836](https://govukverify.atlassian.net/browse/DFC-836)
[DFC-836]: https://govukverify.atlassian.net/browse/DFC-836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DFC-836): License added into device intelligence package

- packages/frontend-ui/src/__tests__/index.spec.ts
- packages/frontend-ui/src/index.ts
> fix: updated middleware functions for typescript

- packages/alpha-app/.env
- packages/alpha-app/src/config/nunjucks.js
- packages/frontend-ui/components/footer/template.njk
- packages/frontend-ui/components/header/template.njk
Added flag for toggling between May Rebrand and original
- [DFC-838](https://govukverify.atlassian.net/browse/DFC-838)
[DFC-838]: https://govukverify.atlassian.net/browse/DFC-838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Dfc 838 dfc flagging to toggle between header and footer versions

- packages/frontend-ui/components/bases/identity/identity-base-form.njk
- packages/frontend-ui/components/bases/identity/identity-base-page.njk
Updated the identity basefiles to include links to the correct styling
- [DFC-743](https://govukverify.atlassian.net/browse/DFC-743)
[DFC-743]: https://govukverify.atlassian.net/browse/DFC-743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: updated the basefiles to include links to the frontend-ui css

- packages/alpha-app/src/views/common/base.njk
- packages/frontend-ui/components/bases/auth/auth-base.njk
- packages/frontend-ui/components/bases/home/home-base.njk
- packages/frontend-ui/components/bases/identity/identity-base-form.njk
- packages/frontend-ui/components/bases/identity/identity-base-page.njk
- packages/frontend-ui/components/bases/mobile/mobile-base.njk
Adding in basefiles for the non identity repos
- [DFC-830](https://govukverify.atlassian.net/browse/DFC-830)
- [DFC-832](https://govukverify.atlassian.net/browse/DFC-832)
- [DFC-833](https://govukverify.atlassian.net/browse/DFC-833)
[DFC-830]: https://govukverify.atlassian.net/browse/DFC-830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DFC-832]: https://govukverify.atlassian.net/browse/DFC-832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DFC-833]: https://govukverify.atlassian.net/browse/DFC-833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(830,832,833): adding basefiles and cleaning up previous basefiles

- package.json
- packages/frontend-ui/package.json
> fix: updated express to peerDependency

- packages/frontend-analytics/src/cookie/cookie.test.ts
- packages/frontend-analytics/src/cookie/cookie.ts
- [DFC-784](https://govukverify.atlassian.net/browse/DFC-784)
[DFC-784]: https://govukverify.atlassian.net/browse/DFC-784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DFC-784): Dynatrace implemented into the cookie banner

- packages/frontend-ui/locales/cy/translation.json
- packages/frontend-ui/locales/en/translation.json
Changed privacy link to avoid redirect
}
- [DFC-903](https://govukverify.atlassian.net/browse/DFC-903)
[DFC-903]: https://govukverify.atlassian.net/browse/DFC-903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(903): updated privacy link

- packages/alpha-app/test/browser/features/v1/analytics/ga4/ga4FormChangeEvent.feature
- packages/alpha-app/test/browser/features/v1/analytics/ga4/ga4NavigationEvent.feature
- packages/alpha-app/test/browser/step_definitions/analytics.js
- packages/alpha-app/test/browser/step_definitions/common.js
- packages/frontend-analytics/src/analytics/formChangeTracker/formChangeTracker.ts
- packages/frontend-analytics/src/utils/pushToDataLayer.ts
Fix failing integration tests in the Analytics package.
Ticket: 
https://govukverify.atlassian.net/browse/DFC-823
> fix(DFC-823): fix failing integration tests

- packages/frontend-ui/components/bases/mobile/mobile-base.njk
> fix: added fingerprint to basefile

- packages/frontend-ui/package.json
- packages/frontend-ui/rollup.config.js
> fix: changed build folders to seperate front and backend

- packages/frontend-passthrough-headers/src/utils/userIP.ts
- packages/frontend-passthrough-headers/tsconfig.json
This removes a code-smell from the passthrough-headers library.
> refactor: code smell in passthrough headers

- packages/alpha-app/src/views/common/base.njk
- packages/frontend-analytics/README.md
- packages/frontend-analytics/src/analytics/core/core.interface.ts
- packages/frontend-analytics/src/index.ts
This enables optional debug logging in the analytics package.
> feat: add debug logging to analytics package

- packages/frontend-analytics/src/analytics/formErrorTracker/formErrorTracker.ts
- packages/frontend-analytics/src/analytics/formResponseTracker/formResponseTracker.ts
- packages/frontend-analytics/src/analytics/formTracker/formTracker.test.ts
- packages/frontend-analytics/src/analytics/formTracker/formTracker.ts
- packages/frontend-analytics/src/analytics/formTracker/formTrackerUtils/dateUtils/dateUtils.test.ts
- packages/frontend-analytics/src/analytics/formTracker/formTrackerUtils/dateUtils/dateUtils.ts
- packages/frontend-analytics/src/analytics/formTracker/formTrackerUtils/getFieldValues/getFieldValues.ts
- packages/frontend-analytics/src/analytics/formTracker/formTrackerUtils/getHeadingText/getHeadingText.test.ts
- packages/frontend-analytics/src/analytics/formTracker/formTrackerUtils/getHeadingText/getHeadingText.ts
- packages/frontend-analytics/src/analytics/formTracker/formTrackerUtils/getSectionValue/getSectionValue.ts
- packages/frontend-analytics/src/analytics/formTracker/formTrackerUtils/getSubmitUrl/getSubmitUrl.test.ts
- packages/frontend-analytics/src/analytics/formTracker/formTrackerUtils/getSubmitUrl/getSubmitUrl.ts
- packages/frontend-analytics/src/analytics/formTracker/formTrackerUtils/isExcludedType/isExcludedType.test.ts
- packages/frontend-analytics/src/analytics/formTracker/formTrackerUtils/isExcludedType/isExcludedType.ts
- packages/frontend-analytics/src/analytics/formTracker/formTrackerUtils/isFormValid/isFormValid.test.ts
- packages/frontend-analytics/src/analytics/formTracker/formTrackerUtils/isFormValid/isFormValid.ts
> fix(DFC-923): Refactor formTracker

- packages/frontend-ui/components/bases/ipv-core/ipv-core-base.njk
> fix: core basefile fix

- packages/frontend-ui/frontend-src/spinner/__tests__/spinner.test.ts
This adjusts the wait times on tests to make them less flaky.
> test: adjust wait times

- packages/frontend-ui/components/progress-button/template.njk
- [DFC-946](https://govukverify.atlassian.net/browse/DFC-946)
[DFC-946]: https://govukverify.atlassian.net/browse/DFC-946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Dfc 946 progress bttn accessibility

- packages/frontend-ui/README.md
- [DFC-XXX](https://govukverify.atlassian.net/browse/DFC-945)
> chore(DFC-945): add progress button implementation guide

- .vscode/settings.json
- packages/alpha-app/src/frontend-assets/index.js
- packages/frontend-ui/components/progress-button/template.njk
- packages/frontend-ui/frontend-src/index.ts
- packages/frontend-ui/frontend-src/progress-button/progress-button.ts
- packages/frontend-ui/locales/cy/translation.json
- packages/frontend-ui/locales/en/translation.json
Adds additional styling for non javascript users
- [DFC-944](https://govukverify.atlassian.net/browse/DFC-944)
[DFC-944]: https://govukverify.atlassian.net/browse/DFC-944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(944): support for no javascript

- .github/workflows/release.yml
Updating workflow with provenance
- [DFC-768](https://govukverify.atlassian.net/browse/DFC-768)
[DFC-768]: https://govukverify.atlassian.net/browse/DFC-768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(768): updating workflows with provenance verification

- .github/workflows/release.yml
> fix: update node version for release

- packages/alpha-app/package.json
- packages/frontend-analytics/package.json
- packages/frontend-asset-loader/package.json
- packages/frontend-device-intelligence/package.json
- packages/frontend-language-toggle/package.json
- packages/frontend-passthrough-headers/package.json
- packages/frontend-ui/package.json
- packages/frontend-vital-signs/package.json
> fix: updated all package.jsons for OIPC
