.github/workflows/cd.yml

Amend to secrets.PAT to ensure the CD pipeline reads up to the PAT (with the access rights) over the github access token which does not have the read/write access for the changelog

Amend to PAT token

---

.github/workflows/cd.yml

Rename package to govuk-one-login for CD pipeline instrumentation

Amend CD pipeline package naming

---

packages/frontend-vitals-monitoring/src/__test__/maxConcurrentConnections.spec.ts
packages/frontend-vitals-monitoring/src/index.ts
packages/frontend-vitals-monitoring/src/maxConcurrentConnections/maxConcurrentConnections.ts

- Adds a function `calculateMaxConcurrentConnections` to calculate the maximum concurrent connections.
- Adds unit tests to validate the function.
- Add a metric to the log the maximum concurrent connections.
- This value should be calculated based on connections in the last x seconds, where x is the logging interval—eg. if we log every 10 seconds, then the maxConcurrentConnections (ms) is based on responses in the last 10 seconds.
- [DFC-598](https://govukverify.atlassian.net/browse/DFC-598)
1. Run `npm run dev` (live rebuilding) in alpha-app and frontend-vitals-package
2. Observe logs
[DFC-598]: https://govukverify.atlassian.net/browse/DFC-598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DFC-598 - Add Scaling Metric for maxConcurrentConnections

---

packages/alpha-app/src/app.js
packages/frontend-vitals-monitoring/src/__test__/initFromApp.spec.ts
packages/frontend-vitals-monitoring/src/index.ts
packages/frontend-vitals-monitoring/test/createTestApp.ts
packages/frontend-vitals-monitoring/test/testApp.ts

This adds a workaround that allows the package to be initialised from an Express app, which means we can inject it in to `hmpo-app` using the the `middlewareSetupFn`.
- [DFC-594](https://govukverify.atlassian.net/browse/DFC-594)
[DFC-594]: https://govukverify.atlassian.net/browse/DFC-594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(DFC-594): add workaround for HMPO

---

nx.json

This fixes a regression issue with the NX configuration in the CD pipeline: https://github.com/govuk-one-login/govuk-one-login-frontend/actions/runs/10182951625/job/28166735340 

fix: fix nx configuration for CD pipeline

---

nx.json

None of our code is set up to connect to the nx cloud currently, but this provides a hard block against connecting to nx cloud in case code is accidentally added in future that tries to connect to it.

feat: put a hard block on nx connecting to cloud services

---

packages/frontend-analytics/sonar-project.properties

Currently the `frontend-analytics` package is configured to report every branch as `main`, which makes Sonarcloud's reporting misleading. Removing this hard-coding allows it to infer the correct branch based on the action environment.

fix: fix the branch reporting for analytics to Sonarcloud

---

.github/workflows/static-analysis.yml

Currently we only run SonarCloud scans against pull requests. This will make the scans also run against main which should give us better reporting numbers.

feat: run SonarCloud scans on main branch

---

packages/frontend-vital-signs/README.md

Typo in README referring to an non-existent package.

Fixing minor typo in README

---

nx.json
packages/frontend-passthrough-headers/README.md
packages/frontend-passthrough-headers/package.json
packages/frontend-passthrough-headers/project.json
packages/frontend-passthrough-headers/src/__test__/specs/index.spec.ts
packages/frontend-passthrough-headers/src/index.ts
packages/frontend-passthrough-headers/src/utils/logger.ts
packages/frontend-passthrough-headers/src/utils/userIP.ts

To address the challenges Identity teams are facing with the frontend-passthrough-headers package, we are adding an optional customLogger argument to support repositories/teams that use their own logger.
- [DFC-671](https://govukverify.atlassian.net/browse/DFC-671)
[DFC-671]: https://govukverify.atlassian.net/browse/DFC-671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DFC-671]: Add optional customLogger argument, so teams can pass their own logger if needed

---

packages/frontend-language-toggle/package.json
packages/frontend-language-toggle/rollup.config.js
packages/frontend-passthrough-headers/package.json
packages/frontend-passthrough-headers/rollup.config.js

I want to consume these packages from a Typescript project which compiles to CommonJS. This fails compilation because Typescript sees it as an ESM dependency:
```
The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'.
```
The package is dual-published as CJS/ESM already, so it seems to be a case of convincing Node to use the CJS version, and TS that this is going to work.
I could get this working locally by:
- Adding `exports` to the `package.json` (as defined at https://nodejs.org/api/packages.html#conditional-exports)
- Renaming the type definition in the CJS build to `*.d.cts`, so TS recognises it as CJS
The implementation is a bit of a fudge - it would be nice if the …

PYIC-7557 Define package.json exports and use .cts for cjs typedefs

---

.github/workflows/commitlint.yml
.github/workflows/release.yml
.github/workflows/static-analysis.yml

There is an existing bug in nx that causes issues with the package-lock after a release has been run. As a result we need to switch to `npm install` for now to keep things working. Linked issue: https://github.com/nrwl/nx/issues/28051

fix: switch npm ci to npm install

---

packages/frontend-asset-loader/rollup.config.js
packages/frontend-language-toggle/rollup.config.js
packages/frontend-vital-signs/package.json
packages/frontend-vital-signs/rollup.config.js

See https://github.com/govuk-one-login/govuk-one-login-frontend/pull/100 for detail of the original change.
This extends the change to the other packages, and restores it in the language toggle where it had been lost.
- [PYIC-7557](https://govukverify.atlassian.net/browse/PYIC-7557)
Consume package from a Typescript project using CommonJS (not ESM modules) and `module: node16`
[PYIC-7557]: https://govukverify.atlassian.net/browse/PYIC-7557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build: support common-js type definitions

---

.github/workflows/static-analysis.yml
package-lock.json
packages/alpha-app/package.json
packages/alpha-app/src/views/common/base.njk
packages/alpha-app/test/browser/features/v1/analytics/ga4/ga4FormChangeEvent.feature
packages/alpha-app/test/browser/features/v1/analytics/ga4/ga4NavigationEvent.feature

Run integration tests for alpha-app as part of the CI pipeline only when alpha-app or one of its dependencies has changed. To do this I had to:
- Install `start-server-and-test` as a devDependency for alpha-app.
- Add a new script to `alpha-app` package.json to start the server and run integration tests.
- Add a script to the CI pipeline to run integration tests.
- Comment out failing integration tests due to the recent upgrade to the latest version of the `frontend-analytics` package. These issues will be addressed in a future ticket.
- Update the `window.DI.appInit` call in alpha-app to reflect the new version of the `frontend-analytics` package.
- [DFC-713](https://govukverify.atlassian.net/browse/DFC-713)
Test by pulling my branch down and running:
`npx nx affected -t lint test build …

DFC-713:  Run alpha app e2e tests as part of pipeline

---

.github/workflows/static-analysis.yml
packages/alpha-app/package.json
packages/frontend-passthrough-headers/package.json
packages/frontend-passthrough-headers/rollup.config.js
packages/frontend-vital-signs/package.json
packages/frontend-vital-signs/rollup.config.js

For Frontend Vitals and Frontend Passthrough Headers (using Frontend Language Toggle as a standard):
- Updates `rollup.config.js` to add a build folder
- Update the `files` prop of `package.json` to include the compiled files only
N/A - Chore
- Run the build script for the vitals package
- Verify a build folder is generated
- Verify the build folder contains everything required in a release
- Repeat for the passthrough headers package

fix(vitals and headers): update build config to include required release files

---

.github/workflows/deprecate.yml

Adds `cache-dependency-path` to the `deprecate.yml` workflow due to the error:
Adding this property in will specify the package-lock for the targeted package
- [DFC-714](https://govukverify.atlassian.net/browse/DFC-714)
Unable to be tested locally
[DFC-714]: https://govukverify.atlassian.net/browse/DFC-714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dfc-714): Specify cache-dependency-path for lock files

---

packages/frontend-language-toggle/src/template.njk

Small change which has been raised 
Remove spacing within the <a> tag
- [DFC-766](https://govukverify.atlassian.net/browse/DFC-XXX)](https://govukverify.atlassian.net/browse/DFC-766)
Within the repo - tested on alpha app
Start the development server by running `npm run dev`.
Start the development process by running `npm run dev`.
Screenshot evidence: 
[DFC-766]: https://govukverify.atlassian.net/browse/DFC-766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(766): update styling on language toggle

---

packages/alpha-app/package.json
packages/alpha-app/src/app.js
packages/frontend-vital-signs/README.md
packages/frontend-vital-signs/src/metrics/eventLoopDelay.ts

This amends the frontend-vital-signs package to report on max event loop delay within the given interval rather than average.
- [DFC-776](https://govukverify.atlassian.net/browse/DFC-776)
Included in the JIRA issue.
[DFC-776]: https://govukverify.atlassian.net/browse/DFC-776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(DFC-776): use max event loop delay in interval rather than mean

---

packages/frontend-analytics/src/analytics/navigationTracker/navigationTracker.test.ts
packages/frontend-analytics/src/analytics/navigationTracker/navigationTracker.ts

- [DFC-771](https://govukverify.atlassian.net/browse/DFC-771)
This is specific to the `di-account-management-frontend` repo (Home)
- Build this branch locally
- In the `di-account-management-frontend` repo
- `npm install`
- Replace the installed `analytics.js` file in the home repo with the locally generated one from this branch
- With docker desktop running, run. `docker compose build && docker compose up`
- Open `localhost:6001` in the Google Tag Assistant
- Verify that navigation tracking works as expected
NOTE: The home repo requires an up to date `.env` and `seed.yaml` file to build properly. These can be provided by the Home team or myself
We DO NOT fire navigation tracking for the following:
- The clicked element is not an anchor or a button
- The clicked element is a button …

fix(DFC-771): Add updated header tracking

---

packages/frontend-analytics/src/analytics/core/core.interface.ts
packages/frontend-analytics/src/analytics/core/core.ts
packages/frontend-analytics/src/analytics/formResponseTracker/formResponseTracker.test.ts
packages/frontend-analytics/src/analytics/formResponseTracker/formResponseTracker.ts

Adds `isPageSensitive` level control for the PII remover from the form response tracker
- [DFC-804](https://govukverify.atlassian.net/browse/DFC-804)
Needs to be locally tested in a consuming repository (KBV preferably)
Global TRUE, Page FALSE
Both FALSE
Global FALSE, Page TRUE
Both TRUE
[DFC-804]: https://govukverify.atlassian.net/browse/DFC-804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(dfc-804): add page level sensitivity flag

---

packages/frontend-ui/components/_all.scss
packages/frontend-ui/components/header/locales/cy/translation.json
packages/frontend-ui/components/header/locales/en/translation.json
packages/frontend-ui/locales/cy/translation.json
packages/frontend-ui/locales/en/translation.json
packages/frontend-ui/src/all.scss
packages/frontend-ui/src/index.ts

This fix removes the header translations from the header component to the central translations. The corresponding middleware has also been updated.
The `@import` SCSS syntax is deprecated, usage has been updated with `@use`
No ticket
- N/A
- N/A
- N/A

fix(frontend-ui): Move Header Translations

---

package-lock.json
packages/frontend-ui/package.json

Updating `tsx` which should remove the last security flag against the repo.

chore: update tsx to remove last vulnerability

---

packages/frontend-analytics/src/analytics/formResponseTracker/formResponseTracker.ts

After a discussion with Sam Evatt yesterday, a new requirement is for the page sensitivity to be marked as true by default. This is due to the approach the data analytics team will take with the roll out. They will be providing a list of pages where the flag needs to be off to each team. As the flag is optional, switching the default value to true means each pod will only need to modified the required pages.
N/A
- Build the analytics package
- This functionality should be tested in the KBV repository. Install node_modules for this repo and then replace the frontend-analytics lib/analytics.js file with the one generated in the monorepo as part of the first step
- Add this line of code to the `questions` page:
```
{% set isPageDataSensitive = false %}
- Turn the global `isDataSensitive` …
```

fix(analytics): Change page sensitivity to on by default

---

packages/alpha-app/package.json
packages/alpha-app/test/browser/features/v1/ fingerprint/thumbmark.feature
packages/alpha-app/test/browser/step_definitions/thumbmark.steps.js

E2E Testing in the alpha app to enable tests to check if the fingerprint is set as a cookie. There is one more E2E test to write for refreshing the webpage but currently in its form this PR has been opened to commit and push work to main to help teams test their implementation with running E2E teams for when teams are implementing the fingerprint code.
- [DFC-824](https://govukverify.atlassian.net/browse/DFC-824)
[DFC-824]: https://govukverify.atlassian.net/browse/DFC-824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DFC-824 thumbmarkjs alpha app testing

---

packages/alpha-app/.env
packages/frontend-ui/components/header/template.njk

Updating how the header template is built to ensure compatibility with teams that are still passing params into the header. Removes risks of breaking changes / workarounds needing created as we roll out the new templates to teams.
Also updated how the tudor crown is created based on how the govuk frontend team have implemented it here: https://design-system.service.gov.uk/components/header/
Also set the alpha app default to false for the May_2025_Rebrand

fix: updated header template to support potentially needed params

---

packages/frontend-ui/components/phase-banner/template.njk
packages/frontend-ui/locales/cy/translation.json
packages/frontend-ui/locales/en/translation.json

This removes a surplus aria-label from the phased banner that has been read out by screenreaders instead of the more helpful content of the element.

fix: remove surplus aria label that confused screen readers

---

packages/frontend-ui/src/__tests__/index.spec.ts
packages/frontend-ui/src/index.ts

Updated the contactUsUrl to remove query parameters from the end of the fromUrl= 

fix: removed parameters from contactUsUrl

---

.github/workflows/static-analysis.yml

Fix to exclude non-publishable packages from static-analysis.

ci: fix static analysis workflow to exlude non-publishable packages

---

packages/alpha-app/test/browser/features/v1/analytics/ga4/ga4PageViewEvent.feature
packages/alpha-app/test/browser/step_definitions/analytics.js
packages/frontend-analytics/src/analytics/core/core.test.ts
packages/frontend-analytics/src/analytics/core/core.ts
packages/frontend-analytics/src/analytics/formChangeTracker/formChangeTracker.test.ts
packages/frontend-analytics/src/analytics/formChangeTracker/formChangeTracker.ts
packages/frontend-analytics/src/analytics/formErrorTracker/formErrorTracker.test.ts
packages/frontend-analytics/src/analytics/formErrorTracker/formErrorTracker.ts
packages/frontend-analytics/src/analytics/formResponseTracker/formResponseTracker.test.ts
packages/frontend-analytics/src/analytics/formResponseTracker/formResponseTracker.ts
packages/frontend-analytics/src/analytics/formTracker/formTracker.test.ts
packages/frontend-analytics/src/analytics/formTracker/formTracker.ts
packages/frontend-analytics/src/analytics/navigationTracker/navigationTracker.test.ts
packages/frontend-analytics/src/analytics/navigationTracker/navigationTracker.ts
packages/frontend-analytics/src/analytics/pageViewTracker/pageViewTracker.test.ts
packages/frontend-analytics/src/analytics/pageViewTracker/pageViewTracker.ts
packages/frontend-analytics/src/analytics/selectContentTracker/selectContentTracker.test.ts
packages/frontend-analytics/src/analytics/selectContentTracker/selectContentTracker.ts
packages/frontend-analytics/src/cookie/cookie.test.ts
packages/frontend-analytics/src/cookie/cookie.ts
packages/frontend-analytics/src/index.test.ts
packages/frontend-analytics/src/utils/dataScrapersUtils/dataScrapers.ts
packages/frontend-analytics/test/utils.ts

This refactor breaks the confusing dependency between the onPageLoad tracker and the formError tracker. Each can now fire or not fire independently without the configuration of one leaking in to the other.

fix: break the dependency between onPageLoad and formError trackers

---

packages/frontend-ui/components/progress-button/template.njk

Ensure the progress button has the `data-prevent-double-click` attribute turned on, so users can't double click.
- [DFC-942](https://govukverify.atlassian.net/browse/DFC-942)
[DFC-942]: https://govukverify.atlassian.net/browse/DFC-942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(dfc-942): prevent double clicking on progress button
